// Deutsch. Most of these are the strings claudiostat.zolfer.com shows in its demo.
extension Strings {
    nonisolated static let de: [String: String] = [
        "about": "Über ClaudioStat",
        "app_icon": "App-Symbol",
        "applications_only": "ClaudioStat aktualisiert sich nur, wenn es aus dem Ordner „Programme“ läuft.",
        "auto": "Automatisch suchen",
        "available": "ClaudioStat {version} ist verfügbar",
        "both": "Symbol und Zahlen",
        "budget": "Budget",
        "budget_day": "Budget pro Tag",
        "budget_hour": "Budget pro Stunde",
        "by": "Von",
        "cancel": "Abbrechen",
        "check": "Nach Updates suchen…",
        "check_connection": "Prüfe deine Verbindung und versuche es erneut.",
        "check_failed": "Suche nach Updates fehlgeschlagen",
        "checking_signature": "Signatur wird geprüft…",
        "click_to_update": "Du hast {version}. Zum Aktualisieren klicken.",
        "daily": "Täglich",
        "data": "Daten",
        "display": "Anzeige",
        "dock": "Im Dock behalten",
        "download": "Download",
        "download_failed": "Der Download ist fehlgeschlagen.",
        "downloading": "Version {version} wird geladen…",
        "every": "Aktualisieren alle",
        "fable": "Fable",
        "failed": "Aktualisierung fehlgeschlagen {time}",
        "flagged_as": "{limit}: {severity}",
        "hours.one": "{n} Stunde",
        "hours.other": "{n} Stunden",
        "icon_only": "Nur Symbol",
        "install_now": "Version {version} jetzt installieren",
        "installed": "Version {version} ist installiert.",
        "installing": "Wird installiert…",
        "language": "Sprache",
        "later": "Später",
        "left": "{n}% übrig.",
        "left_over": "{left}% übrig für {time}",
        "left_resets": "{n}% übrig, Reset in {time}.",
        "limit.fable": "Fable-Limit",
        "limit.session": "Sitzungslimit",
        "limit.week": "Wochenlimit",
        "loading_icon": "Ladeanzeige am Symbol",
        "loading_text": "Ladeanzeige am Text",
        "login": "Beim Anmelden starten",
        "minutes.one": "{n} Minute",
        "minutes.other": "{n} Minuten",
        "never": "Nie",
        "newest": "ClaudioStat {version} ist die neueste verfügbare Version.",
        "not_found": "Claude Code nicht gefunden",
        "not_signed": "Der Download ist nicht von Zolfer Figueiredo signiert.",
        "notice_resets": "Reset in {time}.",
        "notify": "Mitteilungen",
        "notify_marks": "Woche bei 80% und 90%",
        "notify_reached": "Limit erreicht",
        "notify_reset": "Limit zurückgesetzt",
        "now_using": "Du verwendest jetzt ClaudioStat {version}, die neueste verfügbare Version.",
        "numbers_only": "Nur Zahlen",
        "ok": "OK",
        "only": "Nur aktualisieren, wenn Claude geöffnet ist",
        "pace_experimental": "Tempo (experimentell)",
        "paused": "Pausiert · Claude ist nicht geöffnet",
        "paused_updated": "Pausiert · Claude ist nicht geöffnet · aktualisiert {time}",
        "quit": "ClaudioStat beenden",
        "rate_day": "{n} pro Tag",
        "rate_hour": "{n} pro Stunde",
        "reached.fable": "Fable-Limit erreicht",
        "reached.session": "Sitzungslimit erreicht",
        "reached.week": "Wochenlimit erreicht",
        "reason": "Verbrauch {speed}, bis zum Reset reichen {needed}",
        "refresh": "Jetzt aktualisieren",
        "reopen": "Neu öffnen",
        "reopen_failed": "Neu öffnen fehlgeschlagen: {error} Beende die App und öffne sie selbst.",
        "reset_done.fable": "Fable-Limit zurückgesetzt",
        "reset_done.session": "Sitzungslimit zurückgesetzt",
        "reset_done.week": "Wochenlimit zurückgesetzt",
        "resets": "{limit} · Reset in {time}",
        "resets_in": "Reset in",
        "session": "Sitzung",
        "show_data": "Daten unten anzeigen",
        "signed_out": "Zuerst bei Claude Code anmelden (claude ausführen)",
        "span.dh": "{d}T {h}h",
        "span.dh_short": "{d}T{h}h",
        "span.hm": "{h}h {m}min",
        "span.hm_short": "{h}h{mm}",
        "span.m": "{m}min",
        "span.m_short": "{m}min",
        "star_icon": "Schlichter Stern",
        "status": "Claude-Status",
        "tool_failed": "{tool} fehlgeschlagen ({code}).",
        "up_to_date": "Du bist auf dem neuesten Stand!",
        "update_available": "Update verfügbar!",
        "update_complete": "Update abgeschlossen!",
        "update_failed": "Update konnte nicht installiert werden",
        "update_now": "Jetzt installieren",
        "update_question": "Du hast {version}. Jetzt aktualisieren?",
        "updated": "Aktualisiert {time}",
        "updating": "Aktualisiere…",
        "updating_to": "ClaudioStat wird auf {version} aktualisiert",
        "use_again": "Du kannst {name} wieder verwenden.",
        "version": "Version {version}",
        "website": "Website",
        "week": "Woche",
        "week_at": "Woche bei {n}%",
        "weekly": "Wöchentlich",
        "work": "Tägliche Arbeitszeit",
        "working_hours.one": "{n} Arbeitsstunde",
        "working_hours.other": "{n} Arbeitsstunden",
        "wrong_download": "Der Download ist nicht ClaudioStat {version}.",
    ]
}
