// English. Most of these are the strings claudiostat.zolfer.com shows in its demo.
extension Strings {
    nonisolated static let en: [String: String] = [
        "about": "About ClaudioStat",
        "app_icon": "App icon",
        "applications_only": "ClaudioStat updates itself only when it runs from the Applications folder.",
        "auto": "Check automatically",
        "available": "ClaudioStat {version} is available",
        "both": "Icon and numbers",
        "budget": "Budget",
        "budget_day": "Budget per day",
        "budget_hour": "Budget per hour",
        "by": "By",
        "cancel": "Cancel",
        "check": "Check for updates…",
        "check_connection": "Check your connection and try again.",
        "check_failed": "Couldn’t check for updates",
        "checking_signature": "Checking the signature…",
        "click_to_update": "You have {version}. Click to update.",
        "daily": "Daily",
        "data": "Data",
        "display": "Display",
        "dock": "Keep in Dock",
        "download": "Download",
        "download_failed": "The download failed.",
        "downloading": "Downloading version {version}…",
        "every": "Refresh every",
        "fable": "Fable",
        "failed": "Update failed {time}",
        "flagged_as": "{limit}: {severity}",
        "hours.one": "{n} hour",
        "hours.other": "{n} hours",
        "icon_only": "Icon only",
        "install_now": "Install version {version} now",
        "installed": "Version {version} is installed.",
        "installing": "Installing…",
        "language": "Language",
        "later": "Later",
        "left": "{n}% left.",
        "left_over": "{left}% left over {time}",
        "left_resets": "{n}% left, resets in {time}.",
        "limit.fable": "Fable limit",
        "limit.session": "Session limit",
        "limit.week": "Week limit",
        "loading_icon": "Loading icon",
        "loading_text": "Loading text",
        "login": "Launch at login",
        "minutes.one": "{n} minute",
        "minutes.other": "{n} minutes",
        "never": "Never",
        "newest": "ClaudioStat {version} is currently the newest version available.",
        "not_found": "Claude Code not found",
        "not_signed": "The download isn’t signed by Zolfer Figueiredo.",
        "notice_resets": "Resets in {time}.",
        "notify": "Notifications",
        "notify_marks": "Week at 80% and 90%",
        "notify_reached": "Limit reached",
        "notify_reset": "Limit reset",
        "now_using": "You’re now using ClaudioStat {version}, the newest version available.",
        "numbers_only": "Numbers only",
        "ok": "OK",
        "only": "Only refresh while Claude is open",
        "pace_experimental": "Pace (experimental)",
        "paused": "Paused · Claude isn't open",
        "paused_updated": "Paused · Claude isn't open · updated {time}",
        "quit": "Quit ClaudioStat",
        "rate_day": "{n} a day",
        "rate_hour": "{n} an hour",
        "reached.fable": "Fable limit reached",
        "reached.session": "Session limit reached",
        "reached.week": "Week limit reached",
        "reason": "Using {speed}, {needed} lasts until reset",
        "refresh": "Refresh now",
        "reopen": "Reopen",
        "reopen_failed": "Couldn’t reopen: {error} Quit and open it yourself.",
        "reset_done.fable": "Fable limit reset",
        "reset_done.session": "Session limit reset",
        "reset_done.week": "Week limit reset",
        "resets": "{limit} · resets in {time}",
        "resets_in": "Resets in",
        "session": "Session",
        "show_data": "Show data below",
        "signed_out": "Sign in to Claude Code first (run claude)",
        "span.dh": "{d}d {h}h",
        "span.dh_short": "{d}d{h}h",
        "span.hm": "{h}h {m}m",
        "span.hm_short": "{h}h{mm}",
        "span.m": "{m}m",
        "span.m_short": "{m}m",
        "star_icon": "Plain star icon",
        "status": "Claude Status",
        "tool_failed": "{tool} failed ({code}).",
        "up_to_date": "You're up to date!",
        "update_available": "Update available!",
        "update_complete": "Update complete!",
        "update_failed": "Couldn’t install the update",
        "update_now": "Update Now",
        "update_question": "You have {version}. Update now?",
        "updated": "Updated {time}",
        "updating": "Updating…",
        "updating_to": "Updating ClaudioStat to {version}",
        "use_again": "You can use {name} again.",
        "version": "Version {version}",
        "website": "Website",
        "week": "Week",
        "week_at": "Week at {n}%",
        "weekly": "Weekly",
        "work": "Daily working time",
        "working_hours.one": "{n} working hour",
        "working_hours.other": "{n} working hours",
        "wrong_download": "The download isn’t ClaudioStat {version}.",
    ]
}
