// Español. Most of these are the strings claudiostat.zolfer.com shows in its demo.
extension Strings {
    nonisolated static let es: [String: String] = [
        "about": "Acerca de ClaudioStat",
        "add_profile": "Añadir perfil…",
        "app_icon": "Icono de la app",
        "applications_only": "ClaudioStat solo se actualiza cuando se ejecuta desde la carpeta Aplicaciones.",
        "auto": "Buscar automáticamente",
        "available": "ClaudioStat {version} está disponible",
        "both": "Icono y texto",
        "budget": "Presupuesto",
        "budget_day": "Presupuesto por día",
        "budget_hour": "Presupuesto por hora",
        "by": "Por",
        "cancel": "Cancelar",
        "check": "Buscar actualizaciones…",
        "check_connection": "Comprueba tu conexión e inténtalo de nuevo.",
        "check_failed": "No se pudieron buscar actualizaciones",
        "checking_signature": "Comprobando la firma…",
        "choose_folder": "Elige la carpeta de Claude Code de otra cuenta, como .claude-work.",
        "click_to_update": "Tienes la {version}. Haz clic para actualizar.",
        "daily": "Cada día",
        "data": "Datos",
        "display": "Visualización",
        "dock": "Mantener en el Dock",
        "download": "Descargar",
        "download_failed": "La descarga falló.",
        "downloading": "Descargando la versión {version}…",
        "every": "Actualizar cada",
        "fable": "Fable",
        "failed": "Error al actualizar a las {time}",
        "flagged_as": "{limit}: {severity}",
        "hours.one": "{n} hora",
        "hours.other": "{n} horas",
        "icon_only": "Solo el icono",
        "install_now": "Instalar la versión {version} ahora",
        "installed": "La versión {version} está instalada.",
        "installing": "Instalando…",
        "language": "Idioma",
        "later": "Más tarde",
        "left": "{n}% restante.",
        "left_over": "{left}% restante para {time}",
        "left_resets": "{n}% restante, se reinicia en {time}.",
        "limit.fable": "Límite de Fable",
        "limit.session": "Límite de sesión",
        "limit.week": "Límite semanal",
        "loading_icon": "Carga en el icono",
        "loading_text": "Carga en el texto",
        "login": "Abrir al iniciar sesión",
        "minutes.one": "{n} minuto",
        "minutes.other": "{n} minutos",
        "never": "Nunca",
        "newest": "ClaudioStat {version} es la versión más reciente disponible.",
        "not_found": "No se encontró Claude Code",
        "not_signed": "La descarga no está firmada por Zolfer Figueiredo.",
        "notice_resets": "Se reinicia en {time}.",
        "notify": "Notificaciones",
        "notify_marks": "Semana al 80% y al 90%",
        "notify_reached": "Límite alcanzado",
        "notify_reset": "Límite reiniciado",
        "now_using": "Ahora usas ClaudioStat {version}, la versión más reciente disponible.",
        "ok": "OK",
        "only": "Actualizar solo con Claude abierto",
        "pace_experimental": "Ritmo (experimental)",
        "paused": "En pausa · Claude no está abierto",
        "paused_updated": "En pausa · Claude no está abierto · actualizado a las {time}",
        "profile": "Perfil",
        "profile_name": "Nombre del perfil",
        "quit": "Salir de ClaudioStat",
        "rate_day": "{n} al día",
        "rate_hour": "{n} por hora",
        "reached.fable": "Límite de Fable alcanzado",
        "reached.session": "Límite de sesión alcanzado",
        "reached.week": "Límite semanal alcanzado",
        "reason": "Usas {speed}, {needed} dura hasta el reinicio",
        "refresh": "Actualizar ahora",
        "remove": "Quitar",
        "remove_info": "ClaudioStat deja de mostrarlo. La carpeta y su sesión quedan como están.",
        "remove_profile": "Quitar perfil",
        "remove_question": "¿Quitar el perfil {name}?",
        "reopen": "Volver a abrir",
        "reopen_failed": "No se pudo volver a abrir: {error} Sal de la app y ábrela tú.",
        "reset_done.fable": "Límite de Fable reiniciado",
        "reset_done.session": "Límite de sesión reiniciado",
        "reset_done.week": "Límite semanal reiniciado",
        "resets": "{limit} · se reinicia en {time}",
        "resets_in": "Se reinicia en",
        "session": "Sesión",
        "show_data": "Mostrar datos abajo",
        "signed_out": "Inicia sesión en Claude Code primero (ejecuta claude)",
        "span.dh": "{d}d {h}h",
        "span.dh_short": "{d}d{h}h",
        "span.hm": "{h}h {m}min",
        "span.hm_short": "{h}h{mm}",
        "span.m": "{m}min",
        "span.m_short": "{m}min",
        "star_icon": "Icono de estrella simple",
        "status": "Estado de Claude",
        "text_only": "Solo texto",
        "tool_failed": "{tool} falló ({code}).",
        "up_to_date": "¡Estás al día!",
        "update_available": "¡Actualización disponible!",
        "update_complete": "¡Actualización completada!",
        "update_failed": "No se pudo instalar la actualización",
        "update_now": "Instalar ahora",
        "update_question": "Tienes la {version}. ¿Actualizar ahora?",
        "updated": "Actualizado a las {time}",
        "updating": "Actualizando…",
        "updating_to": "Actualizando ClaudioStat a {version}",
        "use_again": "Puedes volver a usar {name}.",
        "version": "Versión {version}",
        "website": "Sitio web",
        "week": "Semana",
        "week_at": "Semana al {n}%",
        "weekly": "Cada semana",
        "work": "Jornada diaria",
        "working_hours.one": "{n} hora laborable",
        "working_hours.other": "{n} horas laborables",
        "wrong_download": "La descarga no es ClaudioStat {version}.",
    ]
}
