// Français. Most of these are the strings claudiostat.zolfer.com shows in its demo.
extension Strings {
    nonisolated static let fr: [String: String] = [
        "about": "À propos de ClaudioStat",
        "add_a_profile": "Ajoutez un profil",
        "add_profile": "Ajouter un profil…",
        "app_icon": "Icône de l’app",
        "applications_only": "ClaudioStat ne se met à jour que lorsqu’il est lancé depuis le dossier Applications.",
        "auto": "Vérifier automatiquement",
        "available": "ClaudioStat {version} est disponible",
        "both": "Icône et texte",
        "budget": "Budget",
        "budget_day": "Budget par jour",
        "budget_hour": "Budget par heure",
        "by": "Par",
        "cancel": "Annuler",
        "check": "Rechercher les mises à jour…",
        "check_connection": "Vérifiez votre connexion et réessayez.",
        "check_failed": "Impossible de rechercher les mises à jour",
        "checking_signature": "Vérification de la signature…",
        "click_to_update": "Vous avez la {version}. Cliquez pour mettre à jour.",
        "connected": "{name} est connecté. Vos limites sont dans la barre des menus.",
        "daily": "Chaque jour",
        "data": "Données",
        "display": "Affichage",
        "dock": "Garder dans le Dock",
        "download": "Télécharger",
        "download_failed": "Le téléchargement a échoué.",
        "downloading": "Téléchargement de la version {version}…",
        "every": "Actualiser toutes les",
        "fable": "Fable",
        "failed": "Échec de l’actualisation à {time}",
        "flagged_as": "{limit} : {severity}",
        "get_claude_code": "Obtenir Claude Code",
        "hours.one": "{n} heure",
        "hours.other": "{n} heures",
        "icon_only": "Icône seule",
        "install_now": "Installer la version {version} maintenant",
        "installed": "La version {version} est installée.",
        "installing": "Installation…",
        "language": "Langue",
        "later": "Plus tard",
        "left": "{n}% restants.",
        "left_over": "{left}% restants sur {time}",
        "left_resets": "{n}% restants, réinitialisation dans {time}.",
        "limit.fable": "Limite Fable",
        "limit.session": "Limite de session",
        "limit.week": "Limite hebdomadaire",
        "loading_icon": "Chargement sur l’icône",
        "loading_text": "Chargement sur le texte",
        "login": "Ouvrir à la connexion",
        "minutes.one": "{n} minute",
        "minutes.other": "{n} minutes",
        "multiple_users": "Plusieurs utilisateurs",
        "never": "Jamais",
        "newest": "ClaudioStat {version} est la version la plus récente.",
        "no_answer": "Claude Code n’a pas répondu. Vérifiez votre connexion ou mettez à jour Claude Code, puis réessayez.",
        "not_found": "Claude Code introuvable",
        "not_signed": "Le téléchargement n’est pas signé par Zolfer Figueiredo.",
        "notice_resets": "Réinitialisation dans {time}.",
        "notify": "Notifications",
        "notify_marks": "Semaine à 80% et 90%",
        "notify_reached": "Limite atteinte",
        "notify_reset": "Limite réinitialisée",
        "now_using": "Vous utilisez maintenant ClaudioStat {version}, la version la plus récente.",
        "ok": "OK",
        "only": "Pause si Claude est fermé",
        "pace_experimental": "Rythme (expérimental)",
        "paused": "En pause · Claude n’est pas ouvert",
        "paused_updated": "En pause · Claude n’est pas ouvert · actualisé à {time}",
        "profile": "Profils",
        "profile_name": "Nom du profil",
        "quit": "Quitter ClaudioStat",
        "rate_day": "{n} par jour",
        "rate_hour": "{n} par heure",
        "reached.fable": "Limite Fable atteinte",
        "reached.session": "Limite de session atteinte",
        "reached.week": "Limite hebdomadaire atteinte",
        "reason": "Usage {speed}, pour tenir {needed}",
        "refresh": "Actualiser maintenant",
        "remove": "Retirer",
        "remove_info": "ClaudioStat cesse de l’afficher et le déconnecte de Claude Code, dans le Terminal aussi. Pour le réutiliser, il faudra vous reconnecter.",
        "remove_profile": "Retirer le profil",
        "remove_question": "Retirer le profil {name} ?",
        "reopen": "Rouvrir",
        "reopen_failed": "Impossible de rouvrir : {error} Quittez l’app et ouvrez-la vous-même.",
        "reset_done.fable": "Limite Fable réinitialisée",
        "reset_done.session": "Limite de session réinitialisée",
        "reset_done.week": "Limite hebdomadaire réinitialisée",
        "resets": "{limit} · réinitialisation dans {time}",
        "resets_in": "Réinitialisation dans",
        "session": "Session",
        "show_data": "Afficher les données ci-dessous",
        "sign_in": "Se connecter",
        "sign_in_info": "Votre navigateur s’ouvre pour vous connecter. Choisissez le compte Claude dont vous voulez voir les limites.",
        "signed_out": "Se connecter à Claude Code…",
        "signing_in": "Terminez la connexion dans votre navigateur…",
        "single_user": "Un seul utilisateur",
        "span.dh": "{d} j {h} h",
        "span.dh_short": "{d}j{h}h",
        "span.hm": "{h} h {m} min",
        "span.hm_short": "{h}h{mm}",
        "span.m": "{m} min",
        "span.m_short": "{m}min",
        "star_icon": "Étoile simple",
        "status": "État de Claude",
        "text_only": "Texte seul",
        "tool_failed": "{tool} a échoué ({code}).",
        "try_again": "Réessayer",
        "up_to_date": "Vous êtes à jour !",
        "update_available": "Mise à jour disponible !",
        "update_complete": "Mise à jour terminée !",
        "update_failed": "Impossible d’installer la mise à jour",
        "update_now": "Mettre à jour",
        "update_question": "Vous avez la {version}. Mettre à jour maintenant ?",
        "updated": "Actualisé à {time}",
        "updating": "Actualisation…",
        "updating_to": "Mise à jour de ClaudioStat vers {version}",
        "use_again": "Vous pouvez de nouveau utiliser {name}.",
        "version": "Version {version}",
        "website": "Site web",
        "week": "Semaine",
        "week_at": "Semaine à {n}%",
        "weekly": "Chaque semaine",
        "work": "Temps de travail quotidien",
        "working_hours.one": "{n} heure ouvrée",
        "working_hours.other": "{n} heures ouvrées",
        "wrong_download": "Le téléchargement n’est pas ClaudioStat {version}.",
    ]
}
