// Italiano. Most of these are the strings claudiostat.zolfer.com shows in its demo.
extension Strings {
    nonisolated static let it: [String: String] = [
        "about": "Informazioni su ClaudioStat",
        "add_a_profile": "Aggiungi un profilo",
        "add_profile": "Aggiungi profilo…",
        "app_icon": "Icona dell’app",
        "applications_only": "ClaudioStat si aggiorna da solo soltanto se viene eseguito dalla cartella Applicazioni.",
        "auto": "Cerca automaticamente",
        "available": "ClaudioStat {version} è disponibile",
        "both": "Icona e testo",
        "budget": "Budget",
        "budget_day": "Budget al giorno",
        "budget_hour": "Budget all’ora",
        "by": "Di",
        "cancel": "Annulla",
        "check": "Cerca aggiornamenti…",
        "check_connection": "Controlla la connessione e riprova.",
        "check_failed": "Impossibile cercare aggiornamenti",
        "checking_signature": "Verifica della firma…",
        "click_to_update": "Hai la {version}. Fai clic per aggiornare.",
        "connected": "{name} è collegato. I tuoi limiti sono nella barra dei menu.",
        "daily": "Ogni giorno",
        "data": "Dati",
        "display": "Visualizzazione",
        "dock": "Mantieni nel Dock",
        "dock_restart": "Riavvia il Dock",
        "dock_restart_text": "Per cambiarlo, macOS deve riavviare il Dock. Lo schermo e la barra dei menu lampeggeranno per un attimo.",
        "dock_restart_title": "Riavviare il Dock?",
        "download": "Scarica",
        "download_failed": "Download non riuscito.",
        "downloading": "Download della versione {version}…",
        "every": "Aggiorna ogni",
        "fable": "Fable",
        "failed": "Aggiornamento non riuscito alle {time}",
        "flagged_as": "{limit}: {severity}",
        "get_claude_code": "Scarica Claude Code",
        "hours.one": "{n} ora",
        "hours.other": "{n} ore",
        "icon_only": "Solo icona",
        "install_now": "Installa ora la versione {version}",
        "installed": "La versione {version} è installata.",
        "installing": "Installazione…",
        "language": "Lingua",
        "later": "Più tardi",
        "left": "{n}% rimasto.",
        "left_over": "{left}% rimasto per {time}",
        "left_resets": "{n}% rimasto, si azzera tra {time}.",
        "limit.fable": "Limite Fable",
        "limit.session": "Limite di sessione",
        "limit.week": "Limite settimanale",
        "loading_icon": "Caricamento sull’icona",
        "loading_text": "Caricamento sul testo",
        "login": "Apri all’accesso",
        "minutes.one": "{n} minuto",
        "minutes.other": "{n} minuti",
        "multiple_users": "Più utenti",
        "never": "Mai",
        "newest": "ClaudioStat {version} è la versione più recente disponibile.",
        "no_answer": "Claude Code non ha risposto. Controlla la connessione o aggiorna Claude Code, poi riprova.",
        "not_found": "Claude Code non trovato",
        "not_signed": "Il download non è firmato da Zolfer Figueiredo.",
        "notice_resets": "Si azzera tra {time}.",
        "notify": "Notifiche",
        "notify_marks": "Settimana all’80% e al 90%",
        "notify_reached": "Limite raggiunto",
        "notify_reset": "Limite azzerato",
        "now_using": "Ora stai usando ClaudioStat {version}, la versione più recente disponibile.",
        "off": "Disattivato",
        "ok": "OK",
        "only": "Pausa con Claude chiuso",
        "pace_experimental": "Ritmo (sperimentale)",
        "paused": "In pausa · Claude non è aperto",
        "paused_updated": "In pausa · Claude non è aperto · aggiornato alle {time}",
        "profile": "Profili",
        "profile_name": "Nome del profilo",
        "profile_per_block": "Mostra profilo per blocco",
        "profile_per_submenu": "Mostra profilo per sottomenu",
        "quit": "Esci da ClaudioStat",
        "rate_day": "{n} al giorno",
        "rate_hour": "{n} all’ora",
        "reached.fable": "Limite Fable raggiunto",
        "reached.session": "Limite di sessione raggiunto",
        "reached.week": "Limite settimanale raggiunto",
        "reason": "Usi {speed}, {needed} dura fino all’azzeramento",
        "refresh": "Aggiorna ora",
        "remove": "Rimuovi",
        "remove_info": "ClaudioStat smette di mostrarlo e lo disconnette da Claude Code, anche nel Terminale. Per usarlo di nuovo dovrai accedere di nuovo.",
        "remove_profile": "Rimuovi profilo",
        "remove_question": "Rimuovere il profilo {name}?",
        "reopen": "Riapri",
        "reopen_failed": "Impossibile riaprire: {error} Esci dall’app e riaprila tu.",
        "reset_done.fable": "Limite Fable azzerato",
        "reset_done.session": "Limite di sessione azzerato",
        "reset_done.week": "Limite settimanale azzerato",
        "resets": "{limit} · si azzera tra {time}",
        "resets_in": "Si azzera tra",
        "session": "Sessione",
        "show_data": "Mostra i dati qui sotto",
        "sign_in": "Accedi",
        "sign_in_info": "Il browser si apre per l’accesso. Scegli l’account Claude di cui vuoi vedere i limiti.",
        "signed_out": "Accedi a Claude Code…",
        "signing_in": "Completa l’accesso nel browser…",
        "single_user": "Utente singolo",
        "span.dh": "{d}g {h}h",
        "span.dh_short": "{d}g{h}h",
        "span.hm": "{h}h {m}min",
        "span.hm_short": "{h}h{mm}",
        "span.m": "{m}min",
        "span.m_short": "{m}min",
        "star_icon": "Stella semplice",
        "status": "Stato di Claude",
        "text_only": "Solo testo",
        "tool_failed": "{tool} non riuscito ({code}).",
        "try_again": "Riprova",
        "up_to_date": "Hai già l’ultima versione!",
        "update_available": "Aggiornamento disponibile!",
        "update_complete": "Aggiornamento completato!",
        "update_failed": "Impossibile installare l’aggiornamento",
        "update_now": "Installa ora",
        "update_question": "Hai la {version}. Aggiornare ora?",
        "updated": "Aggiornato alle {time}",
        "updating": "Aggiornamento…",
        "updating_to": "Aggiornamento di ClaudioStat alla {version}",
        "use_again": "Puoi usare di nuovo {name}.",
        "version": "Versione {version}",
        "website": "Sito web",
        "week": "Settimana",
        "week_at": "Settimana al {n}%",
        "weekly": "Ogni settimana",
        "work": "Orario di lavoro giornaliero",
        "working_hours.one": "{n} ora lavorativa",
        "working_hours.other": "{n} ore lavorative",
        "wrong_download": "Il download non è ClaudioStat {version}.",
    ]
}
