// 日本語. Most of these are the strings claudiostat.zolfer.com shows in its demo.
extension Strings {
    nonisolated static let ja: [String: String] = [
        "about": "ClaudioStat について",
        "add_a_profile": "プロファイルを追加",
        "add_profile": "プロファイルを追加…",
        "app_icon": "アプリアイコン",
        "applications_only": "ClaudioStat は「アプリケーション」フォルダから実行しているときだけ自動でアップデートします。",
        "auto": "自動で確認",
        "available": "ClaudioStat {version} が利用できます",
        "both": "アイコンとテキスト",
        "budget": "予算",
        "budget_day": "1 日あたりの予算",
        "budget_hour": "1 時間あたりの予算",
        "by": "制作:",
        "cancel": "キャンセル",
        "check": "アップデートを確認…",
        "check_connection": "接続を確認して、もう一度お試しください。",
        "check_failed": "アップデートを確認できませんでした",
        "checking_signature": "署名を確認中…",
        "click_to_update": "現在は {version} です。クリックしてアップデート。",
        "connected": "{name} を接続しました。制限はメニューバーに表示されます。",
        "daily": "毎日",
        "data": "データ",
        "display": "表示",
        "dock": "Dock に残す",
        "download": "ダウンロード",
        "download_failed": "ダウンロードに失敗しました。",
        "downloading": "バージョン {version} をダウンロード中…",
        "every": "更新間隔",
        "fable": "Fable",
        "failed": "{time} の更新に失敗",
        "flagged_as": "{limit}: {severity}",
        "get_claude_code": "Claude Code を入手",
        "hours.other": "{n} 時間",
        "icon_only": "アイコンのみ",
        "install_now": "バージョン {version} を今すぐインストール",
        "installed": "バージョン {version} をインストールしました。",
        "installing": "インストール中…",
        "language": "言語",
        "later": "あとで",
        "left": "残り {n}%。",
        "left_over": "残り {left}% を {time}で",
        "left_resets": "残り {n}%、{time}後にリセット。",
        "limit.fable": "Fable の制限",
        "limit.session": "セッションの制限",
        "limit.week": "週間の制限",
        "loading_icon": "読み込み中のアイコン",
        "loading_text": "読み込み中のテキスト",
        "login": "ログイン時に起動",
        "minutes.other": "{n} 分",
        "multiple_users": "複数ユーザー",
        "never": "しない",
        "newest": "ClaudioStat {version} は現在入手できる最新バージョンです。",
        "no_answer": "Claude Code から応答がありません。接続を確認するか Claude Code をアップデートして、もう一度お試しください。",
        "not_found": "Claude Code が見つかりません",
        "not_signed": "ダウンロードしたファイルには Zolfer Figueiredo の署名がありません。",
        "notice_resets": "{time}後にリセット。",
        "notify": "通知",
        "notify_marks": "週間が 80% と 90% に到達",
        "notify_reached": "制限に到達",
        "notify_reset": "制限をリセット",
        "now_using": "ClaudioStat {version} を使用中です。現在入手できる最新バージョンです。",
        "off": "オフ",
        "ok": "OK",
        "only": "Claude を閉じているときは一時停止",
        "pace_experimental": "ペース（試験的）",
        "paused": "一時停止中 · Claude が開いていません",
        "paused_updated": "一時停止中 · Claude が開いていません · {time} に更新",
        "profile": "プロファイル",
        "profile_name": "プロファイル名",
        "profile_per_block": "プロファイルごとにブロック表示",
        "profile_per_submenu": "プロファイルごとにサブメニュー表示",
        "quit": "ClaudioStat を終了",
        "rate_day": "1 日あたり {n}",
        "rate_hour": "1 時間あたり {n}",
        "reached.fable": "Fable の制限に到達",
        "reached.session": "セッションの制限に到達",
        "reached.week": "週間の制限に到達",
        "reason": "使用は {speed}、リセットまで持つのは {needed}",
        "refresh": "今すぐ更新",
        "remove": "削除",
        "remove_info": "ClaudioStat に表示されなくなり、Claude Code でもサインアウトします（ターミナルでも同様です）。再び使うには、もう一度サインインが必要です。",
        "remove_profile": "プロファイルを削除",
        "remove_question": "プロファイル {name} を削除しますか？",
        "reopen": "開き直す",
        "reopen_failed": "開き直せませんでした: {error} アプリを終了して、自分で開いてください。",
        "reset_done.fable": "Fable の制限がリセットされました",
        "reset_done.session": "セッションの制限がリセットされました",
        "reset_done.week": "週間の制限がリセットされました",
        "resets": "{limit} · {time}後にリセット",
        "resets_in": "リセットまでの時間",
        "session": "セッション",
        "show_data": "下にデータを表示",
        "sign_in": "サインイン",
        "sign_in_info": "ブラウザが開くのでサインインしてください。制限を見たい Claude アカウントを選んでください。",
        "signed_out": "Claude Code にサインイン…",
        "signing_in": "ブラウザでサインインを完了してください…",
        "single_user": "単一ユーザー",
        "span.dh": "{d} 日 {h} 時間",
        "span.dh_short": "{d}日{h}時間",
        "span.hm": "{h} 時間 {m} 分",
        "span.hm_short": "{h}時間{mm}分",
        "span.m": "{m} 分",
        "span.m_short": "{m}分",
        "star_icon": "シンプルな星アイコン",
        "status": "Claude のステータス",
        "text_only": "テキストのみ",
        "tool_failed": "{tool} が失敗しました（{code}）。",
        "try_again": "再試行",
        "up_to_date": "最新の状態です",
        "update_available": "アップデートがあります",
        "update_complete": "アップデート完了",
        "update_failed": "アップデートをインストールできませんでした",
        "update_now": "今すぐアップデート",
        "update_question": "現在は {version} です。今すぐアップデートしますか？",
        "updated": "{time} に更新",
        "updating": "更新中…",
        "updating_to": "ClaudioStat を {version} にアップデート中",
        "use_again": "{name} をまた使えます。",
        "version": "バージョン {version}",
        "website": "Web サイト",
        "week": "週間",
        "week_at": "週間 {n}%",
        "weekly": "毎週",
        "work": "1 日の稼働時間",
        "working_hours.other": "稼働 {n} 時間",
        "wrong_download": "ダウンロードしたファイルは ClaudioStat {version} ではありません。",
    ]
}
