// 한국어. Most of these are the strings claudiostat.zolfer.com shows in its demo.
extension Strings {
    nonisolated static let ko: [String: String] = [
        "about": "ClaudioStat에 관하여",
        "add_a_profile": "프로필을 추가하세요",
        "add_profile": "프로필 추가…",
        "app_icon": "앱 아이콘",
        "applications_only": "ClaudioStat은(는) 응용 프로그램 폴더에서 실행할 때만 스스로 업데이트합니다.",
        "auto": "자동으로 확인",
        "available": "ClaudioStat {version} 사용 가능",
        "both": "아이콘과 텍스트",
        "budget": "예산",
        "budget_day": "하루 예산",
        "budget_hour": "시간당 예산",
        "by": "제작:",
        "cancel": "취소",
        "check": "업데이트 확인…",
        "check_connection": "연결을 확인하고 다시 시도하세요.",
        "check_failed": "업데이트를 확인할 수 없음",
        "checking_signature": "서명 확인 중…",
        "click_to_update": "현재 {version}입니다. 클릭하여 업데이트하세요.",
        "connected": "{name} 계정이 연결되었습니다. 한도는 메뉴 막대에 표시됩니다.",
        "daily": "매일",
        "data": "데이터",
        "display": "표시",
        "dock": "Dock에 유지",
        "dock_restart": "Dock 재시동",
        "dock_restart_text": "이를 변경하려면 macOS가 Dock을 재시동해야 합니다. 화면과 메뉴 막대가 잠깐 깜박입니다.",
        "dock_restart_title": "Dock을 재시동할까요?",
        "download": "다운로드",
        "download_failed": "다운로드에 실패했습니다.",
        "downloading": "버전 {version} 다운로드 중…",
        "every": "새로 고침 간격",
        "fable": "Fable",
        "failed": "{time} 새로 고침 실패",
        "flagged_as": "{limit}: {severity}",
        "get_claude_code": "Claude Code 받기",
        "hours.other": "{n}시간",
        "icon_only": "아이콘만",
        "install_now": "지금 버전 {version} 설치",
        "installed": "버전 {version}이(가) 설치되었습니다.",
        "installing": "설치 중…",
        "language": "언어",
        "later": "나중에",
        "left": "{n}% 남음.",
        "left_over": "{time} 동안 {left}% 남음",
        "left_resets": "{n}% 남음, {time} 후 재설정.",
        "limit.fable": "Fable 한도",
        "limit.session": "세션 한도",
        "limit.week": "주간 한도",
        "loading_icon": "로딩 중 아이콘 효과",
        "loading_text": "로딩 중 텍스트 효과",
        "login": "로그인 시 실행",
        "minutes.other": "{n}분",
        "multiple_users": "여러 사용자",
        "never": "안 함",
        "newest": "ClaudioStat {version}은(는) 현재 사용 가능한 최신 버전입니다.",
        "no_answer": "Claude Code가 응답하지 않았습니다. 연결을 확인하거나 Claude Code를 업데이트한 후 다시 시도하세요.",
        "not_found": "Claude Code를 찾을 수 없음",
        "not_signed": "다운로드한 파일에 Zolfer Figueiredo의 서명이 없습니다.",
        "notice_resets": "{time} 후 재설정.",
        "notify": "알림",
        "notify_marks": "주간 80% 및 90%",
        "notify_reached": "한도 도달",
        "notify_reset": "한도 재설정",
        "now_using": "이제 ClaudioStat {version}을(를) 사용 중입니다. 현재 사용 가능한 최신 버전입니다.",
        "off": "끔",
        "ok": "확인",
        "only": "Claude가 닫혀 있으면 일시 정지",
        "pace_experimental": "속도(실험적)",
        "paused": "일시 정지됨 · Claude가 열려 있지 않음",
        "paused_updated": "일시 정지됨 · Claude가 열려 있지 않음 · {time}에 새로 고침",
        "profile": "프로필",
        "profile_name": "프로필 이름",
        "profile_per_block": "프로필마다 블록으로 보기",
        "profile_per_submenu": "프로필마다 하위 메뉴로 보기",
        "quit": "ClaudioStat 종료",
        "rate_day": "하루 {n}",
        "rate_hour": "시간당 {n}",
        "reached.fable": "Fable 한도 도달",
        "reached.session": "세션 한도 도달",
        "reached.week": "주간 한도 도달",
        "reason": "사용 속도 {speed}, 재설정까지 버티려면 {needed}",
        "refresh": "지금 새로 고침",
        "remove": "제거",
        "remove_info": "ClaudioStat에 더 이상 표시되지 않고 Claude Code에서도 로그아웃됩니다(터미널 포함). 다시 사용하려면 다시 로그인해야 합니다.",
        "remove_profile": "프로필 제거",
        "remove_question": "{name} 프로필을 제거할까요?",
        "reopen": "다시 열기",
        "reopen_failed": "다시 열 수 없음: {error} 앱을 종료한 후 직접 여세요.",
        "reset_done.fable": "Fable 한도 재설정됨",
        "reset_done.session": "세션 한도 재설정됨",
        "reset_done.week": "주간 한도 재설정됨",
        "resets": "{limit} · {time} 후 재설정",
        "resets_in": "재설정까지 남은 시간",
        "session": "세션",
        "show_data": "아래에 데이터 표시",
        "sign_in": "로그인",
        "sign_in_info": "브라우저가 열리면 로그인하세요. 한도를 확인할 Claude 계정을 선택하세요.",
        "signed_out": "Claude Code에 로그인…",
        "signing_in": "브라우저에서 로그인을 완료하세요…",
        "single_user": "단일 사용자",
        "span.dh": "{d}일 {h}시간",
        "span.dh_short": "{d}일{h}시간",
        "span.hm": "{h}시간 {m}분",
        "span.hm_short": "{h}시간{mm}분",
        "span.m": "{m}분",
        "span.m_short": "{m}분",
        "star_icon": "단순한 별 아이콘",
        "status": "Claude 상태",
        "text_only": "텍스트만",
        "tool_failed": "{tool} 실패({code}).",
        "try_again": "다시 시도",
        "up_to_date": "최신 버전입니다!",
        "update_available": "업데이트가 있습니다!",
        "update_complete": "업데이트 완료!",
        "update_failed": "업데이트를 설치할 수 없음",
        "update_now": "지금 업데이트",
        "update_question": "현재 {version}입니다. 지금 업데이트할까요?",
        "updated": "{time}에 새로 고침",
        "updating": "새로 고치는 중…",
        "updating_to": "ClaudioStat을(를) {version}(으)로 업데이트 중",
        "use_again": "{name}을(를) 다시 사용할 수 있습니다.",
        "version": "버전 {version}",
        "website": "웹사이트",
        "week": "주간",
        "week_at": "주간 {n}%",
        "weekly": "매주",
        "work": "하루 근무 시간",
        "working_hours.other": "근무 {n}시간",
        "wrong_download": "다운로드한 파일이 ClaudioStat {version}이(가) 아닙니다.",
    ]
}
