// Polski. Most of these are the strings claudiostat.zolfer.com shows in its demo.
extension Strings {
    nonisolated static let pl: [String: String] = [
        "about": "O ClaudioStat",
        "app_icon": "Ikona aplikacji",
        "applications_only": "ClaudioStat uaktualnia się sam tylko wtedy, gdy działa z folderu Aplikacje.",
        "auto": "Sprawdzaj automatycznie",
        "available": "Dostępna jest wersja ClaudioStat {version}",
        "both": "Ikona i liczby",
        "budget": "Budżet",
        "budget_day": "Budżet na dzień",
        "budget_hour": "Budżet na godzinę",
        "by": "Autor:",
        "cancel": "Anuluj",
        "check": "Sprawdź uaktualnienia…",
        "check_connection": "Sprawdź połączenie i spróbuj ponownie.",
        "check_failed": "Nie udało się sprawdzić uaktualnień",
        "checking_signature": "Sprawdzanie podpisu…",
        "click_to_update": "Masz wersję {version}. Kliknij, aby uaktualnić.",
        "daily": "Codziennie",
        "data": "Dane",
        "display": "Wyświetlanie",
        "dock": "Zostaw w Docku",
        "download": "Pobierz",
        "download_failed": "Pobieranie nie powiodło się.",
        "downloading": "Pobieranie wersji {version}…",
        "every": "Odświeżaj co",
        "fable": "Fable",
        "failed": "Odświeżanie nie powiodło się o {time}",
        "flagged_as": "{limit}: {severity}",
        "hours.few": "{n} godziny",
        "hours.many": "{n} godzin",
        "hours.one": "{n} godzina",
        "hours.other": "{n} godziny",
        "icon_only": "Tylko ikona",
        "install_now": "Zainstaluj teraz wersję {version}",
        "installed": "Wersja {version} jest zainstalowana.",
        "installing": "Instalowanie…",
        "language": "Język",
        "later": "Później",
        "left": "Zostało {n}%.",
        "left_over": "zostało {left}% na {time}",
        "left_resets": "Zostało {n}%, reset za {time}.",
        "limit.fable": "Limit Fable",
        "limit.session": "Limit sesji",
        "limit.week": "Limit tygodnia",
        "loading_icon": "Ładowanie na ikonie",
        "loading_text": "Ładowanie na tekście",
        "login": "Uruchamiaj przy logowaniu",
        "minutes.few": "{n} minuty",
        "minutes.many": "{n} minut",
        "minutes.one": "{n} minutę",
        "minutes.other": "{n} minuty",
        "never": "Nigdy",
        "newest": "ClaudioStat {version} to obecnie najnowsza dostępna wersja.",
        "not_found": "Nie znaleziono Claude Code",
        "not_signed": "Pobrany plik nie jest podpisany przez Zolfer Figueiredo.",
        "notice_resets": "Reset za {time}.",
        "notify": "Powiadomienia",
        "notify_marks": "Tydzień na 80% i 90%",
        "notify_reached": "Limit osiągnięty",
        "notify_reset": "Limit zresetowany",
        "now_using": "Używasz teraz ClaudioStat {version}, najnowszej dostępnej wersji.",
        "numbers_only": "Tylko liczby",
        "ok": "OK",
        "only": "Odświeżaj tylko, gdy Claude jest otwarty",
        "pace_experimental": "Tempo (eksperymentalne)",
        "paused": "Wstrzymano · Claude nie jest otwarty",
        "paused_updated": "Wstrzymano · Claude nie jest otwarty · odświeżono o {time}",
        "quit": "Zakończ ClaudioStat",
        "rate_day": "{n} dziennie",
        "rate_hour": "{n} na godzinę",
        "reached.fable": "Osiągnięto limit Fable",
        "reached.session": "Osiągnięto limit sesji",
        "reached.week": "Osiągnięto limit tygodnia",
        "reason": "Zużycie {speed}, do resetu wystarczy {needed}",
        "refresh": "Odśwież teraz",
        "reopen": "Otwórz ponownie",
        "reopen_failed": "Nie udało się otworzyć ponownie: {error} Zakończ aplikację i otwórz ją samodzielnie.",
        "reset_done.fable": "Limit Fable zresetowany",
        "reset_done.session": "Limit sesji zresetowany",
        "reset_done.week": "Limit tygodnia zresetowany",
        "resets": "{limit} · reset za {time}",
        "resets_in": "Reset za",
        "session": "Sesja",
        "show_data": "Pokaż dane poniżej",
        "signed_out": "Najpierw zaloguj się w Claude Code (uruchom claude)",
        "span.dh": "{d} d {h} godz.",
        "span.dh_short": "{d}d{h}g",
        "span.hm": "{h} godz. {m} min",
        "span.hm_short": "{h}g{mm}",
        "span.m": "{m} min",
        "span.m_short": "{m}min",
        "star_icon": "Zwykła gwiazdka",
        "status": "Status Claude",
        "tool_failed": "{tool}: niepowodzenie ({code}).",
        "up_to_date": "Masz najnowszą wersję!",
        "update_available": "Dostępne uaktualnienie!",
        "update_complete": "Uaktualnienie zakończone!",
        "update_failed": "Nie udało się zainstalować uaktualnienia",
        "update_now": "Uaktualnij teraz",
        "update_question": "Masz wersję {version}. Uaktualnić teraz?",
        "updated": "Odświeżono o {time}",
        "updating": "Odświeżanie…",
        "updating_to": "Uaktualnianie ClaudioStat do {version}",
        "use_again": "Możesz znowu korzystać z {name}.",
        "version": "Wersja {version}",
        "website": "Strona",
        "week": "Tydzień",
        "week_at": "Tydzień na {n}%",
        "weekly": "Co tydzień",
        "work": "Dzienny czas pracy",
        "working_hours.few": "{n} godziny pracy",
        "working_hours.many": "{n} godzin pracy",
        "working_hours.one": "{n} godzinę pracy",
        "working_hours.other": "{n} godziny pracy",
        "wrong_download": "Pobrany plik to nie ClaudioStat {version}.",
    ]
}
