// Português. Most of these are the strings claudiostat.zolfer.com shows in its demo.
extension Strings {
    nonisolated static let pt: [String: String] = [
        "about": "Sobre o ClaudioStat",
        "add_a_profile": "Adicione um perfil",
        "add_profile": "Adicionar perfil…",
        "app_icon": "Ícone do app",
        "applications_only": "O ClaudioStat só se atualiza quando é executado da pasta Aplicativos.",
        "auto": "Verificar automaticamente",
        "available": "ClaudioStat {version} está disponível",
        "both": "Ícone e texto",
        "budget": "Orçamento",
        "budget_day": "Orçamento por dia",
        "budget_hour": "Orçamento por hora",
        "by": "Por",
        "cancel": "Cancelar",
        "check": "Buscar atualizações…",
        "check_connection": "Verifique sua conexão e tente de novo.",
        "check_failed": "Não foi possível buscar atualizações",
        "checking_signature": "Verificando a assinatura…",
        "click_to_update": "Você tem a {version}. Clique para atualizar.",
        "connected": "{name} está conectado. Seus limites estão na barra de menus.",
        "daily": "Diariamente",
        "data": "Dados",
        "display": "Exibição",
        "dock": "Manter no Dock",
        "dock_restart": "Reiniciar o Dock",
        "dock_restart_text": "Para mudar isso, o macOS precisa reiniciar o Dock. A tela e a barra de menus vão piscar por um instante.",
        "dock_restart_title": "Reiniciar o Dock?",
        "download": "Baixar",
        "download_failed": "O download falhou.",
        "downloading": "Baixando a versão {version}…",
        "every": "Atualizar a cada",
        "fable": "Fable",
        "failed": "Falha ao atualizar às {time}",
        "flagged_as": "{limit}: {severity}",
        "get_claude_code": "Baixar o Claude Code",
        "hours.one": "{n} hora",
        "hours.other": "{n} horas",
        "icon_only": "Só o ícone",
        "install_now": "Instalar a versão {version} agora",
        "installed": "A versão {version} está instalada.",
        "installing": "Instalando…",
        "language": "Idioma",
        "later": "Depois",
        "left": "{n}% restantes.",
        "left_over": "{left}% restantes para {time}",
        "left_resets": "{n}% restantes, reinicia em {time}.",
        "limit.fable": "Limite do Fable",
        "limit.session": "Limite da sessão",
        "limit.week": "Limite da semana",
        "loading_icon": "Carregamento no ícone",
        "loading_text": "Carregamento no texto",
        "login": "Abrir ao iniciar sessão",
        "minutes.one": "{n} minuto",
        "minutes.other": "{n} minutos",
        "multiple_users": "Vários usuários",
        "never": "Nunca",
        "newest": "ClaudioStat {version} é a versão mais recente disponível.",
        "no_answer": "O Claude Code não respondeu. Verifique sua conexão ou atualize o Claude Code e tente de novo.",
        "not_found": "Claude Code não encontrado",
        "not_signed": "O download não está assinado por Zolfer Figueiredo.",
        "notice_resets": "Reinicia em {time}.",
        "notify": "Notificações",
        "notify_marks": "Semana em 80% e 90%",
        "notify_reached": "Limite atingido",
        "notify_reset": "Limite reiniciado",
        "now_using": "Agora você está usando o ClaudioStat {version}, a versão mais recente disponível.",
        "off": "Desligado",
        "ok": "OK",
        "only": "Pausar com o Claude fechado",
        "pace": "Ritmo",
        "paused": "Pausado · o Claude não está aberto",
        "paused_updated": "Pausado · o Claude não está aberto · atualizado às {time}",
        "profile": "Perfis",
        "profile_name": "Nome do perfil",
        "profile_per_block": "Mostrar perfil por bloco",
        "profile_per_submenu": "Mostrar perfil por submenu",
        "quit": "Encerrar ClaudioStat",
        "rate_day": "{n} por dia",
        "rate_hour": "{n} por hora",
        "reached.fable": "Limite do Fable atingido",
        "reached.session": "Limite da sessão atingido",
        "reached.week": "Limite da semana atingido",
        "reason": "Usando {speed}, {needed} dura até o reinício",
        "refresh": "Atualizar agora",
        "remove": "Remover",
        "remove_info": "O ClaudioStat deixa de mostrá-lo e encerra o login dele no Claude Code, no Terminal também. Para usá-lo de novo, é preciso entrar outra vez.",
        "remove_profile": "Remover perfil",
        "remove_question": "Remover o perfil {name}?",
        "reopen": "Reabrir",
        "reopen_failed": "Não foi possível reabrir: {error} Encerre o app e abra-o você mesmo.",
        "reset_done.fable": "Limite do Fable reiniciado",
        "reset_done.session": "Limite da sessão reiniciado",
        "reset_done.week": "Limite da semana reiniciado",
        "resets": "{limit} · reinicia em {time}",
        "resets_in": "Reinicia em",
        "session": "Sessão",
        "show_data": "Mostrar dados abaixo",
        "sign_in": "Entrar",
        "sign_in_info": "Seu navegador abre para você entrar. Escolha a conta do Claude cujos limites você quer ver.",
        "signed_out": "Entrar no Claude Code…",
        "signing_in": "Termine de entrar no seu navegador…",
        "single_user": "Um só usuário",
        "span.dh": "{d}d {h}h",
        "span.dh_short": "{d}d{h}h",
        "span.hm": "{h}h {m}min",
        "span.hm_short": "{h}h{mm}",
        "span.m": "{m}min",
        "span.m_short": "{m}min",
        "star_icon": "Ícone de estrela simples",
        "status": "Status do Claude",
        "text_only": "Só o texto",
        "tool_failed": "{tool} falhou ({code}).",
        "try_again": "Tentar de novo",
        "up_to_date": "Você está atualizado!",
        "update_available": "Atualização disponível!",
        "update_complete": "Atualização concluída!",
        "update_failed": "Não foi possível instalar a atualização",
        "update_now": "Instalar agora",
        "update_question": "Você tem a {version}. Atualizar agora?",
        "updated": "Atualizado às {time}",
        "updating": "Atualizando…",
        "updating_to": "Atualizando ClaudioStat para {version}",
        "use_again": "Você pode usar o {name} de novo.",
        "version": "Versão {version}",
        "website": "Site",
        "week": "Semana",
        "week_at": "Semana em {n}%",
        "weekly": "Semanalmente",
        "work": "Tempo de trabalho diário",
        "working_hours.one": "{n} hora útil",
        "working_hours.other": "{n} horas úteis",
        "wrong_download": "O download não é o ClaudioStat {version}.",
    ]
}
