// Русский. Most of these are the strings claudiostat.zolfer.com shows in its demo.
extension Strings {
    nonisolated static let ru: [String: String] = [
        "about": "О программе ClaudioStat",
        "add_profile": "Добавить профиль…",
        "app_icon": "Значок приложения",
        "applications_only": "ClaudioStat обновляется сам, только если запущен из папки «Программы».",
        "auto": "Проверять автоматически",
        "available": "Доступна версия ClaudioStat {version}",
        "both": "Значок и текст",
        "budget": "Бюджет",
        "budget_day": "Бюджет на день",
        "budget_hour": "Бюджет на час",
        "by": "Автор:",
        "cancel": "Отменить",
        "check": "Проверить обновления…",
        "check_connection": "Проверьте подключение и повторите попытку.",
        "check_failed": "Не удалось проверить обновления",
        "checking_signature": "Проверка подписи…",
        "click_to_update": "У вас {version}. Нажмите, чтобы обновить.",
        "connected": "{name} подключён. Ваши лимиты в строке меню.",
        "daily": "Ежедневно",
        "data": "Данные",
        "display": "Вид",
        "dock": "Оставить в Dock",
        "download": "Скачать",
        "download_failed": "Не удалось загрузить.",
        "downloading": "Загрузка версии {version}…",
        "every": "Интервал обновления",
        "fable": "Fable",
        "failed": "Не удалось обновить в {time}",
        "flagged_as": "{limit}: {severity}",
        "get_claude_code": "Скачать Claude Code",
        "hours.few": "{n} часа",
        "hours.many": "{n} часов",
        "hours.one": "{n} час",
        "hours.other": "{n} часа",
        "icon_only": "Только значок",
        "install_now": "Установить версию {version} сейчас",
        "installed": "Версия {version} установлена.",
        "installing": "Установка…",
        "language": "Язык",
        "later": "Позже",
        "left": "Осталось {n}%.",
        "left_over": "осталось {left}% на {time}",
        "left_resets": "Осталось {n}%, сброс через {time}.",
        "limit.fable": "Лимит Fable",
        "limit.session": "Лимит сессии",
        "limit.week": "Лимит недели",
        "loading_icon": "Загрузка на значке",
        "loading_text": "Загрузка в тексте",
        "login": "Запускать при входе",
        "minutes.few": "{n} минуты",
        "minutes.many": "{n} минут",
        "minutes.one": "{n} минута",
        "minutes.other": "{n} минуты",
        "multiple_users": "Несколько пользователей",
        "never": "Никогда",
        "newest": "ClaudioStat {version}: это самая новая доступная версия.",
        "no_answer": "Claude Code не ответил. Проверьте подключение или обновите Claude Code и повторите попытку.",
        "not_found": "Claude Code не найден",
        "not_signed": "Загрузка не подписана Zolfer Figueiredo.",
        "notice_resets": "Сброс через {time}.",
        "notify": "Уведомления",
        "notify_marks": "Неделя на 80% и 90%",
        "notify_reached": "Лимит исчерпан",
        "notify_reset": "Лимит сброшен",
        "now_using": "Теперь вы используете ClaudioStat {version}, самую новую доступную версию.",
        "ok": "OK",
        "only": "Пауза, когда Claude закрыт",
        "pace_experimental": "Темп (эксперимент)",
        "paused": "Пауза · Claude не открыт",
        "paused_updated": "Пауза · Claude не открыт · обновлено в {time}",
        "profile": "Профиль",
        "profile_name": "Имя профиля",
        "quit": "Завершить ClaudioStat",
        "rate_day": "{n} в день",
        "rate_hour": "{n} в час",
        "reached.fable": "Лимит Fable исчерпан",
        "reached.session": "Лимит сессии исчерпан",
        "reached.week": "Лимит недели исчерпан",
        "reason": "Расход {speed}, до сброса хватит при {needed}",
        "refresh": "Обновить сейчас",
        "remove": "Удалить",
        "remove_info": "ClaudioStat перестанет его показывать. Папка и вход в ней останутся как есть.",
        "remove_profile": "Удалить профиль",
        "remove_question": "Удалить профиль {name}?",
        "reopen": "Открыть снова",
        "reopen_failed": "Не удалось открыть снова: {error} Завершите приложение и откройте его сами.",
        "reset_done.fable": "Лимит Fable сброшен",
        "reset_done.session": "Лимит сессии сброшен",
        "reset_done.week": "Лимит недели сброшен",
        "resets": "{limit} · сброс через {time}",
        "resets_in": "Время до сброса",
        "session": "Сессия",
        "show_data": "Показывать данные ниже",
        "sign_in": "Войти",
        "sign_in_info": "Откроется браузер, в котором вы войдёте. Выберите аккаунт Claude, лимиты которого хотите видеть.",
        "signed_out": "Войти в Claude Code…",
        "signing_in": "Завершите вход в браузере…",
        "single_user": "Один пользователь",
        "span.dh": "{d} д {h} ч",
        "span.dh_short": "{d}д{h}ч",
        "span.hm": "{h} ч {m} мин",
        "span.hm_short": "{h}ч{mm}",
        "span.m": "{m} мин",
        "span.m_short": "{m}мин",
        "star_icon": "Простая звезда",
        "status": "Статус Claude",
        "text_only": "Только текст",
        "tool_failed": "{tool}: сбой ({code}).",
        "try_again": "Повторить",
        "up_to_date": "У вас последняя версия!",
        "update_available": "Доступно обновление!",
        "update_complete": "Обновление завершено!",
        "update_failed": "Не удалось установить обновление",
        "update_now": "Установить сейчас",
        "update_question": "У вас {version}. Обновить сейчас?",
        "updated": "Обновлено в {time}",
        "updating": "Обновление…",
        "updating_to": "Обновление ClaudioStat до {version}",
        "use_again": "{name} снова можно использовать.",
        "version": "Версия {version}",
        "website": "Сайт",
        "week": "Неделя",
        "week_at": "Неделя: {n}%",
        "weekly": "Еженедельно",
        "work": "Рабочее время в день",
        "working_hours.few": "{n} рабочих часа",
        "working_hours.many": "{n} рабочих часов",
        "working_hours.one": "{n} рабочий час",
        "working_hours.other": "{n} рабочего часа",
        "wrong_download": "Загружен не ClaudioStat {version}.",
    ]
}
