// Українська. Most of these are the strings claudiostat.zolfer.com shows in its demo.
extension Strings {
    nonisolated static let uk: [String: String] = [
        "about": "Про ClaudioStat",
        "add_profile": "Додати профіль…",
        "app_icon": "Іконка застосунку",
        "applications_only": "ClaudioStat оновлюється сам, лише коли запущений із папки «Програми».",
        "auto": "Перевіряти автоматично",
        "available": "Доступна версія ClaudioStat {version}",
        "both": "Іконка й текст",
        "budget": "Бюджет",
        "budget_day": "Бюджет на день",
        "budget_hour": "Бюджет на годину",
        "by": "Автор:",
        "cancel": "Скасувати",
        "check": "Перевірити оновлення…",
        "check_connection": "Перевірте з’єднання та спробуйте ще раз.",
        "check_failed": "Не вдалося перевірити оновлення",
        "checking_signature": "Перевірка підпису…",
        "click_to_update": "У вас {version}. Натисніть, щоб оновити.",
        "connected": "{name} під’єднано. Ваші ліміти в рядку меню.",
        "daily": "Щодня",
        "data": "Дані",
        "display": "Вигляд",
        "dock": "Залишити в Dock",
        "download": "Завантажити",
        "download_failed": "Не вдалося завантажити.",
        "downloading": "Завантаження версії {version}…",
        "every": "Інтервал оновлення",
        "fable": "Fable",
        "failed": "Не вдалось оновити о {time}",
        "flagged_as": "{limit}: {severity}",
        "get_claude_code": "Завантажити Claude Code",
        "hours.few": "{n} години",
        "hours.many": "{n} годин",
        "hours.one": "{n} година",
        "hours.other": "{n} години",
        "icon_only": "Лише іконка",
        "install_now": "Встановити версію {version} зараз",
        "installed": "Версію {version} встановлено.",
        "installing": "Встановлення…",
        "language": "Мова",
        "later": "Пізніше",
        "left": "Лишилося {n}%.",
        "left_over": "лишилося {left}% на {time}",
        "left_resets": "Лишилося {n}%, скидання через {time}.",
        "limit.fable": "Ліміт Fable",
        "limit.session": "Ліміт сесії",
        "limit.week": "Ліміт тижня",
        "loading_icon": "Завантаження на іконці",
        "loading_text": "Завантаження в тексті",
        "login": "Запускати під час входу",
        "minutes.few": "{n} хвилини",
        "minutes.many": "{n} хвилин",
        "minutes.one": "{n} хвилина",
        "minutes.other": "{n} хвилини",
        "multiple_users": "Кілька користувачів",
        "never": "Ніколи",
        "newest": "ClaudioStat {version}: це найновіша доступна версія.",
        "no_answer": "Claude Code не відповів. Перевірте з’єднання або оновіть Claude Code і спробуйте ще раз.",
        "not_found": "Claude Code не знайдено",
        "not_signed": "Завантаження не підписано Zolfer Figueiredo.",
        "notice_resets": "Скидання через {time}.",
        "notify": "Сповіщення",
        "notify_marks": "Тиждень на 80% і 90%",
        "notify_reached": "Ліміт вичерпано",
        "notify_reset": "Ліміт скинуто",
        "now_using": "Тепер ви використовуєте ClaudioStat {version}, найновішу доступну версію.",
        "ok": "OK",
        "only": "Пауза, коли Claude закрито",
        "pace_experimental": "Темп (експеримент)",
        "paused": "Пауза · Claude не відкрито",
        "paused_updated": "Пауза · Claude не відкрито · оновлено о {time}",
        "profile": "Профіль",
        "profile_name": "Назва профілю",
        "quit": "Завершити ClaudioStat",
        "rate_day": "{n} на день",
        "rate_hour": "{n} на годину",
        "reached.fable": "Ліміт Fable вичерпано",
        "reached.session": "Ліміт сесії вичерпано",
        "reached.week": "Ліміт тижня вичерпано",
        "reason": "Витрата {speed}, до скидання вистачить за {needed}",
        "refresh": "Оновити зараз",
        "remove": "Вилучити",
        "remove_info": "ClaudioStat більше не показуватиме його. Тека та вхід у ній залишаться як є.",
        "remove_profile": "Вилучити профіль",
        "remove_question": "Вилучити профіль {name}?",
        "reopen": "Відкрити знову",
        "reopen_failed": "Не вдалося відкрити знову: {error} Завершіть програму й відкрийте її самі.",
        "reset_done.fable": "Ліміт Fable скинуто",
        "reset_done.session": "Ліміт сесії скинуто",
        "reset_done.week": "Ліміт тижня скинуто",
        "resets": "{limit} · скидання через {time}",
        "resets_in": "Час до скидання",
        "session": "Сесія",
        "show_data": "Показувати дані нижче",
        "sign_in": "Увійти",
        "sign_in_info": "Відкриється браузер, у якому ви ввійдете. Виберіть обліковий запис Claude, ліміти якого хочете бачити.",
        "signed_out": "Увійти в Claude Code…",
        "signing_in": "Завершіть вхід у браузері…",
        "single_user": "Один користувач",
        "span.dh": "{d} д {h} год",
        "span.dh_short": "{d}д{h}г",
        "span.hm": "{h} год {m} хв",
        "span.hm_short": "{h}г{mm}",
        "span.m": "{m} хв",
        "span.m_short": "{m}хв",
        "star_icon": "Проста зірка",
        "status": "Статус Claude",
        "text_only": "Лише текст",
        "tool_failed": "{tool}: збій ({code}).",
        "try_again": "Спробувати ще раз",
        "up_to_date": "У вас найновіша версія!",
        "update_available": "Доступне оновлення!",
        "update_complete": "Оновлення завершено!",
        "update_failed": "Не вдалося встановити оновлення",
        "update_now": "Встановити зараз",
        "update_question": "У вас {version}. Оновити зараз?",
        "updated": "Оновлено о {time}",
        "updating": "Оновлення…",
        "updating_to": "Оновлення ClaudioStat до {version}",
        "use_again": "{name} знову можна використовувати.",
        "version": "Версія {version}",
        "website": "Сайт",
        "week": "Тиждень",
        "week_at": "Тиждень: {n}%",
        "weekly": "Щотижня",
        "work": "Робочий час на день",
        "working_hours.few": "{n} робочі години",
        "working_hours.many": "{n} робочих годин",
        "working_hours.one": "{n} робочу годину",
        "working_hours.other": "{n} робочої години",
        "wrong_download": "Завантажено не ClaudioStat {version}.",
    ]
}
