// 中文. Most of these are the strings claudiostat.zolfer.com shows in its demo.
extension Strings {
    nonisolated static let zh: [String: String] = [
        "about": "关于 ClaudioStat",
        "add_a_profile": "添加个人资料",
        "add_profile": "添加个人资料…",
        "app_icon": "应用图标",
        "applications_only": "ClaudioStat 仅在从“应用程序”文件夹运行时才会自行更新。",
        "auto": "自动检查",
        "available": "ClaudioStat {version} 已可用",
        "both": "图标和文字",
        "budget": "预算",
        "budget_day": "每天预算",
        "budget_hour": "每小时预算",
        "by": "作者:",
        "cancel": "取消",
        "check": "检查更新…",
        "check_connection": "请检查网络连接后重试。",
        "check_failed": "无法检查更新",
        "checking_signature": "正在检查签名…",
        "click_to_update": "当前版本为 {version}。点按即可更新。",
        "connected": "{name} 已连接。你的限额显示在菜单栏中。",
        "daily": "每天",
        "data": "数据",
        "display": "显示",
        "dock": "保留在 Dock 中",
        "download": "下载",
        "download_failed": "下载失败。",
        "downloading": "正在下载版本 {version}…",
        "every": "刷新间隔",
        "fable": "Fable",
        "failed": "刷新失败 {time}",
        "flagged_as": "{limit}：{severity}",
        "get_claude_code": "获取 Claude Code",
        "hours.other": "{n} 小时",
        "icon_only": "仅图标",
        "install_now": "立即安装版本 {version}",
        "installed": "版本 {version} 已安装。",
        "installing": "正在安装…",
        "language": "语言",
        "later": "稍后",
        "left": "剩余 {n}%。",
        "left_over": "剩余 {left}%，可用 {time}",
        "left_resets": "剩余 {n}%，{time}后重置。",
        "limit.fable": "Fable 限额",
        "limit.session": "会话限额",
        "limit.week": "每周限额",
        "loading_icon": "图标加载动画",
        "loading_text": "文字加载动画",
        "login": "登录时启动",
        "minutes.other": "{n} 分钟",
        "multiple_users": "多个用户",
        "never": "从不",
        "newest": "ClaudioStat {version} 是目前最新的版本。",
        "no_answer": "Claude Code 没有响应。请检查网络连接或更新 Claude Code，然后重试。",
        "not_found": "未找到 Claude Code",
        "not_signed": "下载的文件不是由 Zolfer Figueiredo 签名的。",
        "notice_resets": "{time}后重置。",
        "notify": "通知",
        "notify_marks": "每周达到 80% 和 90%",
        "notify_reached": "限额已用完",
        "notify_reset": "限额已重置",
        "now_using": "你现在使用的是 ClaudioStat {version}，这是目前最新的版本。",
        "ok": "好",
        "only": "Claude 关闭时暂停",
        "pace_experimental": "速度（实验性）",
        "paused": "已暂停 · Claude 未打开",
        "paused_updated": "已暂停 · Claude 未打开 · 刷新于 {time}",
        "profile": "个人资料",
        "profile_name": "个人资料名称",
        "quit": "退出 ClaudioStat",
        "rate_day": "每天 {n}",
        "rate_hour": "每小时 {n}",
        "reached.fable": "Fable 限额已用完",
        "reached.session": "会话限额已用完",
        "reached.week": "每周限额已用完",
        "reason": "用量{speed}，要撑到重置需{needed}",
        "refresh": "立即刷新",
        "remove": "移除",
        "remove_info": "ClaudioStat 将不再显示它，并在 Claude Code 中退出它的登录，终端里也一样。要再次使用，需要重新登录。",
        "remove_profile": "移除个人资料",
        "remove_question": "移除个人资料 {name}？",
        "reopen": "重新打开",
        "reopen_failed": "无法重新打开：{error} 请退出应用后自行打开。",
        "reset_done.fable": "Fable 限额已重置",
        "reset_done.session": "会话限额已重置",
        "reset_done.week": "每周限额已重置",
        "resets": "{limit} · {time}后重置",
        "resets_in": "重置倒计时",
        "session": "会话",
        "show_data": "在下方显示数据",
        "sign_in": "登录",
        "sign_in_info": "浏览器会打开供你登录。请选择你想查看其限额的 Claude 账户。",
        "signed_out": "登录 Claude Code…",
        "signing_in": "请在浏览器中完成登录…",
        "single_user": "单个用户",
        "span.dh": "{d} 天 {h} 小时",
        "span.dh_short": "{d}天{h}时",
        "span.hm": "{h} 小时 {m} 分",
        "span.hm_short": "{h}时{mm}分",
        "span.m": "{m} 分钟",
        "span.m_short": "{m}分",
        "star_icon": "简洁星形图标",
        "status": "Claude 状态",
        "text_only": "仅文字",
        "tool_failed": "{tool} 失败（{code}）。",
        "try_again": "重试",
        "up_to_date": "已是最新版本！",
        "update_available": "有可用更新！",
        "update_complete": "更新完成！",
        "update_failed": "无法安装更新",
        "update_now": "立即更新",
        "update_question": "当前版本为 {version}。现在更新吗？",
        "updated": "刷新于 {time}",
        "updating": "正在刷新…",
        "updating_to": "正在将 ClaudioStat 更新到 {version}",
        "use_again": "可以再次使用 {name} 了。",
        "version": "版本 {version}",
        "website": "网站",
        "week": "本周",
        "week_at": "本周已用 {n}%",
        "weekly": "每周",
        "work": "每日工作时长",
        "working_hours.other": "{n} 个工作小时",
        "wrong_download": "下载的文件不是 ClaudioStat {version}。",
    ]
}
